// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC42uvKFEaWgtG91jwWMdU3u25oKoyd2Ek',
    appId: '1:668701996723:web:9fb8a006e3e535acc362c6',
    messagingSenderId: '668701996723',
    projectId: 'hackit25-59f91',
    authDomain: 'hackit25-59f91.firebaseapp.com',
    storageBucket: 'hackit25-59f91.firebasestorage.app',
    measurementId: 'G-N49LPRQ6BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoY0leCUQvSoeNwxbPBvy4s_I0hlo0mLU',
    appId: '1:668701996723:android:3c9bdde67d992ec3c362c6',
    messagingSenderId: '668701996723',
    projectId: 'hackit25-59f91',
    storageBucket: 'hackit25-59f91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA22kkGCk1LD92QCDPRysUervsiJZbqzrY',
    appId: '1:668701996723:ios:a3dc1eefeb8090afc362c6',
    messagingSenderId: '668701996723',
    projectId: 'hackit25-59f91',
    storageBucket: 'hackit25-59f91.firebasestorage.app',
    iosBundleId: 'com.example.hackit2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA22kkGCk1LD92QCDPRysUervsiJZbqzrY',
    appId: '1:668701996723:ios:a3dc1eefeb8090afc362c6',
    messagingSenderId: '668701996723',
    projectId: 'hackit25-59f91',
    storageBucket: 'hackit25-59f91.firebasestorage.app',
    iosBundleId: 'com.example.hackit2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC42uvKFEaWgtG91jwWMdU3u25oKoyd2Ek',
    appId: '1:668701996723:web:9f811f2a3634999bc362c6',
    messagingSenderId: '668701996723',
    projectId: 'hackit25-59f91',
    authDomain: 'hackit25-59f91.firebaseapp.com',
    storageBucket: 'hackit25-59f91.firebasestorage.app',
    measurementId: 'G-WTS4YGJ719',
  );

}